# Generated by Django 2.2.6 on 2021-03-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210308_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Выберите группу', max_length=200, verbose_name='Название группы'),
        ),
    ]
